# Generated by Django 5.2.15 on 2026-06-30 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authprovideraccount',
            name='unique_auth_provider_user_id',
        ),
        migrations.AddConstraint(
            model_name='authprovideraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_user_id', ''), _negated=True), fields=('provider', 'provider_user_id'), name='unique_auth_provider_user_id'),
        ),
    ]
