# Generated by Django 5.2.15 on 2026-07-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_refactor_user_profile_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_usernam_65d164_idx',
            old_name='users_user_usernam_idx',
        ),
    ]
